name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug :beetle:"]
assignees:
  - twiddli
body:
  - type: markdown
    attributes:
      value: |
        Do NOT use this template for support requests. If you have a question, please ask in the [Discussions](https://github.com/iSplasher/PlayniteExtensions/discussions).
  - type: input
    id: plugin
    attributes:
      label: Plugin
      description: Which plugin does this relate to?
      placeholder: ex. Virtual Library
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Plugin version
      description: What version of the plugin are you running?
      placeholder: ex. 1.0.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: If you can, also include a clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what the issue is. Screenshots are welcome!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant extension log output
      description: |
        Please copy and paste any relevant log output. You can open the `extensions.log` from the Playnite menu.
        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Did you check for similar issues?
      description: Please check the [issue tracker](https://github.com/iSplasher/PlayniteExtensions/issues) for similar issues.
      options:
        - label: I checked and didn't find similar issues.
          required: true
